# spring boot
spring:
  output: {ansi: {enabled: ALWAYS}}
  mvc: {log-request-details: true}
  jackson: {serialization: {WRITE_DATES_AS_TIMESTAMPS: false}}
  jpa:
    generate-ddl: true
    hibernate: {ddl-auto: create-drop}
    show-sql: false
    properties: {hibernate: {dialect: org.hibernate.dialect.PostgreSQLDialect}}
  datasource:
    url: "jdbc:postgresql://${QPROV_DB_HOST:127.0.0.1}:${QPROV_DB_PORT:5432}/${QPROV_DB_DATABASE:qprov}"
    driver-class-name: org.postgresql.Driver
    username: "${QPROV_DB_USERNAME:qprov}"
    password: "${QPROV_DB_PASSWORD:qprov}"
    initialization-mode: always
    continue-on-error: true
    sql-script-encoding: UTF-8

# tomcat
server:
  port: ${SERVER_PORT:8081}
  servlet:
    contextPath: "/qprov-collector"

# logging
logging:
  level:
    mvc: "${LOGGING_LEVEL_MVC:debug}"
    org.quantil.qprov: "${LOGGING_LEVEL_QPROV:debug}"
    springdoc: "${LOGGING_LEVEL_SPRINGDOC:debug}"
    springframework: "${LOGGING_LEVEL_SPRINGFRAMEWORK:debug}"
    web: "${LOGGING_LEVEL_WEB:debug}"
