openapi: "3.0.0"
info:
  description: "QProv API."
  version: "0.0.1"
  title: "QProv"
  contact: {email: "b@benleb.de"}
  license: {name: "Apache 2.0", url: "http://www.apache.org/licenses/LICENSE-2.0.html"}
components:
  schemas:
    Providers: {type: array, items: {$ref: "#/components/schemas/Provider"}}
    Provider:
      type: object
      properties:
        id: {type: string}
        name: {type: string}
        url: {type: string}
        devices:
          type: array
          items: {type: string}
    Machines:
      type: array
      items:
        $ref: "#/components/schemas/Machine"
    Machine:
      type: object
      properties:
        id: {type: string}
        name: {type: string}
        qubits:
          type: array
          items:
            $ref: "#/components/schemas/Qubit"
    Qubit:
      type: object
      properties:
        id: {type: string}
        attribute1: {type: string}
        attribute2: {type: number}
paths:
  /providers:
    get:
      summary: Returns a list of quantum computing resource providers.
      responses:
        "200":
          description: A JSON array of Providers
          content:
            application/json:
              schema: {$ref: "#/components/schemas/Providers"}
  /machines:
    get:
      summary: Returns a list of quantum computing device (QCD).
      responses:
        "200":
          description: A JSON array of QCDs
          content:
            application/json:
              schema: {$ref: "#/components/schemas/Machines"}
  /machines/{machineId}:
    get:
      summary: Returns a QCD by ID.
      parameters:
        - name: machineId
          in: path
          required: true
          description: Machine ID of a QCD
          schema: {type: string}
      responses:
        "200": {description: OK}
