# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: Push docker images to Dockerhub

on:
  push:
    branches: master
    tags:
      - "v*.*.*"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - 
        name: Set reference as output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      -
        name: Build and push QProv Web latest
        if: ${{ steps.vars.outputs.tag }} == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-Web
          push: true
          tags: planqk/qprov:latest
      -
        name: Build and push QProv Web version 
        if: ${{ steps.vars.outputs.tag }} != 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-Web
          push: true
          tags: planqk/qprov:${{ steps.vars.outputs.tag }}
      -
        name: Build and push QProv Collector latest
        if: ${{ steps.vars.outputs.tag }} == 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-Collector
          push: true
          tags: planqk/qprov-collector:latest
      -
        name: Build and push QProv Collector version 
        if: ${{ steps.vars.outputs.tag }} != 'master'
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile-Web
          push: true
          tags: planqk/qprov-collector:${{ steps.vars.outputs.tag }}
          
