# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven
name: build images

on:
  push: {branches: [master]}
  pull_request: {branches: [master]}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: set up Java 14
        uses: actions/setup-java@v1
        with: {java-version: 14}

      - name: login to ghcr.io
        # new ghcr.io needs a PAT as repo secret -> using deprecated docker.pkg registry
        # run: echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
        run: echo "${{ github.token }}" | docker login https://docker.pkg.github.com -u "${GITHUB_ACTOR}" --password-stdin

      - name: build project & images
        run: mvn -U -T 1C clean install spring-boot:build-image

        # disabled (added an "echo") as the account quota seems reached, sorry :/
      - name: push images to ghcr.io (disabled)
        # new ghcr.io needs a PAT as repo secret -> using deprecated docker.pkg registry
        # run: for module in api collector; do docker push ghcr.io/ust-quantil/qprov/${module}; done
        run: for module in api collector; do echo docker push docker.pkg.github.com/ust-quantil/qprov/${module}; done

      - name: deploy artifacts to maven.pkg.github.com
        run: mvn deploy
        # fails due to missing authentication/permissions
        continue-on-error: true
